module.exports = {
  dependencies: [
    'apollo-server-hapi',
    '@hapi/hapi',
    '@hapi/vision',
    '@hapi/inert',
    '@hapi/good',
    '@hapi/good-console',
    'blipp',
    'bookshelf',
    'hapi-router',
    'graphql',
    'jsonwebtoken',
    'knex',
    'pg',
    'xtconf',
    'bcrypt',
  ],
  devDependencies: ['nodemon', 'npm-run-all', 'typesetter'],
}
