module.exports = {
  dependencies: [
    '@hapi/hapi',
    '@hapi/vision',
    '@hapi/inert',
    '@hapi/good',
    '@hapi/good-console',
    'blipp',
    'bookshelf',
    'hapi-router',
    'graphi',
    'graphql',
    'jsonwebtoken',
    'knex',
    'pg',
    'xtconf',
    'bcrypt',
  ],
  devDependencies: ['nodemon', 'typesetter'],
}
