module.exports = {
  dependencies: [
    'react',
    'react-dom',
    'react-form-elements',
    '@reach/router',
    '@brightleaf/react-hooks',
  ],
  devDependencies: [
    '@babel/core',
    '@babel/plugin-proposal-class-properties',
    '@babel/plugin-syntax-dynamic-import',
    '@babel/preset-env',
    '@babel/preset-react',
    'babel-eslint',
    'babel-loader',
    'babel-jest',
    'copy-webpack-plugin',
    'css-loader',
    'html-webpack-plugin',
    'react-hot-loader',
    'react-testing-library',
    'style-loader',
    'webpack',
    'webpack-cli',
    'webpack-dev-server',
  ],
}
