module.exports = {
  dependencies: [
    'apollo-boost',
    'apollo-cache-inmemory',
    'apollo-client',
    'apollo-link-context',
    'apollo-link-http',
    'react',
    'react-apollo',
    'react-dom',
    'react-form-elements',
    '@reach/router',
    'styled-components',
    'the-platform',
  ],
  devDependencies: [
    '@babel/core',
    '@babel/plugin-proposal-class-properties',
    '@babel/plugin-syntax-dynamic-import',
    '@babel/preset-env',
    '@babel/preset-react',
    'babel-eslint',
    'babel-loader',
    'babel-jest',
    'babel-plugin-styled-components',
    'css-loader',
    'html-webpack-plugin',
    'react-hot-loader',
    'react-testing-library',
    'style-loader',
    'webpack',
    'webpack-cli',
    'webpack-dev-server',
  ],
}
